### ISSUE TITLE
ForeignKey onDelete/onUpdate

### ISSUE THREAD

**Issue by marcj** [apinnecke/composite-number-range-behavior#1]
We need to specify those attributes. Currently it's only being created without any onDelete/onUpdate value and without the ability to overwrite it.

**Comment by apinnecke** [comment]
:+1: Sounds sane to me. I'll have a look on it in about 2 weeks.

If you can't wait you have to overrride the propel migration by hand i
guess ... :/
Am 09.06.2015 15:21 schrieb "Marc J. Schmidt" <notifications@github.com>:

**Comment by marcj** [comment]
Super tüp :+1:
